### PR TITLE
add createProject method with full params.

### PR DESCRIPTION
**Pull request by lonfee88**

### CODE REVIEW

**Comment by gmessner** [comment]
I very much appreciate your contribution to this project.  Unfortunately, I just did a major merge into the source and cannot auto-merge your pull request.

Could you pull the latest and make the same changes and then resubmit a new pull request?

If not, I can manually merge your changes.

Thanks,
Greg

**Comment by lonfee88** [comment]
I'll open a new one.

**Comment by lonfee88** [comment]
PUT mehtod is not workable at all.

**Comment by lonfee88** [comment]
PUT mehtod is not workable at all.  
https://github.com/lonfee88/gitlab-api/commit/cb0fee18fbfaf95afb1a52143249e85430be1626 fixed it.

**Comment by gmessner** [comment]
I have merged your pull request.

Thank you again for you contributions.

Greg

**Pull request merged**
